apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.name}}
  template:
    metadata:
      labels:
        app: {{gitops.name}}
        version: beta-{{gitops.version}}
        deploy: deploy-{{gitops.deploy}}
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "1000m"
          #   requests:
          #     memory: "512Mi"
          #     cpu: "500m"
          args:
          - {{gitops.config.webvargs}}
          # - -l
          # - "5000"
          # - --prometheus
          # - -r
          # - -s
          # - https://central-tx-austin-101.cseretail.com
          # - https://central-tx-austin-102.cseretail.com
          # - https://central-mo-kc-101.cseretail.com
          # - https://central-mo-kc-102.cseretail.com
          # - https://east-ga-atlanta-101.cseretail.com
          # - https://east-ga-atlanta-102.cseretail.com
          # - https://west-wa-seattle-101.cseretail.com
          # - https://west-wa-seattle-102.cseretail.com
          # - https://west-ca-sd-101.cseretail.com
          # - https://west-ca-sd-102.cseretail.com
          # - -u
          # - https://raw.githubusercontent.com/bartr/tinybench/main/webv/
          # - -f
          # - load.json
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}
          # - --log-format 
          # - Json
          # - --verbose
---
apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}
