name: GitOps Deploy

on:

  push:
    branches:
      - main

    paths:
    - '.github/workflows/gitops.yaml'
    - 'autogitops/**'
    - 'apps/**'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Docker pull
      run: |
        docker pull ghcr.io/bartr/autogitops:latest
    - name: GitOps Deploy
      run: |
        docker run \
        --name ago \
        --rm \
        -v $(pwd):/ago \
        ghcr.io/bartr/autogitops:latest \
        -r /retaildevcrews/red-gitops \
        -p ${{ secrets.GHCR_PAT }}
